package com.ycwl.servebixin.cn.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ycwl.servebixin.cn.db.db.ServePersonnelDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SERVE_PERSONNEL_DB".
*/
public class ServePersonnelDBDao extends AbstractDao<ServePersonnelDB, Long> {

    public static final String TABLENAME = "SERVE_PERSONNEL_DB";

    /**
     * Properties of entity ServePersonnelDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property Nickname = new Property(2, String.class, "nickname", false, "NICKNAME");
        public final static Property Avatar = new Property(3, String.class, "avatar", false, "AVATAR");
        public final static Property SkillPrice = new Property(4, String.class, "skillPrice", false, "SKILL_PRICE");
        public final static Property BixinId = new Property(5, String.class, "bixinId", false, "BIXIN_ID");
        public final static Property Age = new Property(6, String.class, "age", false, "AGE");
        public final static Property Sex = new Property(7, String.class, "sex", false, "SEX");
        public final static Property Constellation = new Property(8, String.class, "constellation", false, "CONSTELLATION");
        public final static Property OccupationName = new Property(9, String.class, "occupationName", false, "OCCUPATION_NAME");
    }


    public ServePersonnelDBDao(DaoConfig config) {
        super(config);
    }
    
    public ServePersonnelDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SERVE_PERSONNEL_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"NICKNAME\" TEXT," + // 2: nickname
                "\"AVATAR\" TEXT," + // 3: avatar
                "\"SKILL_PRICE\" TEXT," + // 4: skillPrice
                "\"BIXIN_ID\" TEXT," + // 5: bixinId
                "\"AGE\" TEXT," + // 6: age
                "\"SEX\" TEXT," + // 7: sex
                "\"CONSTELLATION\" TEXT," + // 8: constellation
                "\"OCCUPATION_NAME\" TEXT);"); // 9: occupationName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SERVE_PERSONNEL_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ServePersonnelDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(3, nickname);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(4, avatar);
        }
 
        String skillPrice = entity.getSkillPrice();
        if (skillPrice != null) {
            stmt.bindString(5, skillPrice);
        }
 
        String bixinId = entity.getBixinId();
        if (bixinId != null) {
            stmt.bindString(6, bixinId);
        }
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(7, age);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(8, sex);
        }
 
        String constellation = entity.getConstellation();
        if (constellation != null) {
            stmt.bindString(9, constellation);
        }
 
        String occupationName = entity.getOccupationName();
        if (occupationName != null) {
            stmt.bindString(10, occupationName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ServePersonnelDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(3, nickname);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(4, avatar);
        }
 
        String skillPrice = entity.getSkillPrice();
        if (skillPrice != null) {
            stmt.bindString(5, skillPrice);
        }
 
        String bixinId = entity.getBixinId();
        if (bixinId != null) {
            stmt.bindString(6, bixinId);
        }
 
        String age = entity.getAge();
        if (age != null) {
            stmt.bindString(7, age);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(8, sex);
        }
 
        String constellation = entity.getConstellation();
        if (constellation != null) {
            stmt.bindString(9, constellation);
        }
 
        String occupationName = entity.getOccupationName();
        if (occupationName != null) {
            stmt.bindString(10, occupationName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ServePersonnelDB readEntity(Cursor cursor, int offset) {
        ServePersonnelDB entity = new ServePersonnelDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nickname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // avatar
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // skillPrice
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // bixinId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // age
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // sex
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // constellation
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // occupationName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ServePersonnelDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAvatar(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSkillPrice(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBixinId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAge(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSex(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setConstellation(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setOccupationName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ServePersonnelDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ServePersonnelDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ServePersonnelDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
